import Foundation

struct CommandEntry: Identifiable, Hashable {
    let id = UUID()
    let rule: String
    let risk: RiskLevel
    let purpose: String
    let danger: String
}

enum CommandCatalog {
    static let all: [CommandEntry] = [
        // ─────── L1 只读（查看/罗列） ───────
        .init(rule: "Bash(ls:*)",               risk: .l1, purpose: "列目录",             danger: "无副作用"),
        .init(rule: "Bash(pwd)",                risk: .l1, purpose: "当前路径",           danger: "无"),
        .init(rule: "Bash(whoami)",             risk: .l1, purpose: "当前用户",           danger: "无"),
        .init(rule: "Bash(hostname)",           risk: .l1, purpose: "主机名",             danger: "无"),
        .init(rule: "Bash(uname:*)",            risk: .l1, purpose: "系统信息",           danger: "无"),
        .init(rule: "Bash(date)",               risk: .l1, purpose: "当前时间",           danger: "无"),
        .init(rule: "Bash(env)",                risk: .l1, purpose: "查看环境变量",       danger: "可能泄露 token/secret"),
        .init(rule: "Bash(which:*)",            risk: .l1, purpose: "查可执行路径",       danger: "无"),
        .init(rule: "Bash(cat:*)",              risk: .l1, purpose: "读文件",             danger: "可能读到敏感文件"),
        .init(rule: "Bash(head:*)",             risk: .l1, purpose: "读前几行",           danger: "同上"),
        .init(rule: "Bash(tail:*)",             risk: .l1, purpose: "读末尾/跟随",         danger: "同上"),
        .init(rule: "Bash(wc:*)",               risk: .l1, purpose: "行数/字数统计",       danger: "无"),
        .init(rule: "Bash(file:*)",             risk: .l1, purpose: "识别文件类型",       danger: "无"),
        .init(rule: "Bash(find:*)",             risk: .l1, purpose: "按条件查找",         danger: "-exec 可执行命令，建议限定"),
        .init(rule: "Bash(grep:*)",             risk: .l1, purpose: "文本搜索",           danger: "无"),
        .init(rule: "Bash(rg:*)",               risk: .l1, purpose: "ripgrep 搜索",       danger: "无"),
        .init(rule: "Bash(awk:*)",              risk: .l1, purpose: "文本处理",           danger: "可写但通常只读"),
        .init(rule: "Bash(sort:*)",             risk: .l1, purpose: "排序",               danger: "无"),
        .init(rule: "Bash(uniq:*)",             risk: .l1, purpose: "去重",               danger: "无"),
        .init(rule: "Bash(diff:*)",             risk: .l1, purpose: "对比文件",           danger: "无"),
        .init(rule: "Bash(jq:*)",               risk: .l1, purpose: "JSON 处理",          danger: "无"),
        .init(rule: "Bash(yq:*)",               risk: .l1, purpose: "YAML 处理",          danger: "无"),
        .init(rule: "Bash(df:*)",               risk: .l1, purpose: "磁盘占用",           danger: "无"),
        .init(rule: "Bash(du:*)",               risk: .l1, purpose: "目录体积",           danger: "无"),
        .init(rule: "Bash(ps:*)",               risk: .l1, purpose: "进程列表",           danger: "可能泄露命令行参数"),
        .init(rule: "Bash(uptime)",             risk: .l1, purpose: "系统运行时间",       danger: "无"),
        .init(rule: "Bash(git status)",         risk: .l1, purpose: "仓库状态",           danger: "无"),
        .init(rule: "Bash(git diff:*)",         risk: .l1, purpose: "查看 diff",           danger: "无"),
        .init(rule: "Bash(git log:*)",          risk: .l1, purpose: "提交历史",           danger: "无"),
        .init(rule: "Bash(git blame:*)",        risk: .l1, purpose: "逐行作者",           danger: "无"),
        .init(rule: "Bash(git show:*)",         risk: .l1, purpose: "查看对象",           danger: "无"),
        .init(rule: "Bash(git branch:*)",       risk: .l1, purpose: "分支列表",           danger: "-D 会删除，见 L5"),
        .init(rule: "Bash(git remote:*)",       risk: .l1, purpose: "remote 信息",         danger: "无"),
        .init(rule: "Bash(git config --get:*)", risk: .l1, purpose: "读 git 配置",         danger: "无"),
        .init(rule: "Bash(go version)",         risk: .l1, purpose: "Go 版本",            danger: "无"),
        .init(rule: "Bash(node --version)",     risk: .l1, purpose: "Node 版本",          danger: "无"),
        .init(rule: "Bash(python --version)",   risk: .l1, purpose: "Python 版本",        danger: "无"),
        .init(rule: "Bash(docker ps:*)",        risk: .l1, purpose: "容器列表",           danger: "无"),
        .init(rule: "Bash(docker images:*)",    risk: .l1, purpose: "镜像列表",           danger: "无"),
        .init(rule: "Bash(docker logs:*)",      risk: .l1, purpose: "容器日志",           danger: "无"),
        .init(rule: "Bash(kubectl get:*)",      risk: .l1, purpose: "查看 K8s 资源",       danger: "无"),
        .init(rule: "Bash(kubectl describe:*)", risk: .l1, purpose: "K8s 详情",           danger: "无"),
        .init(rule: "Bash(kubectl logs:*)",     risk: .l1, purpose: "Pod 日志",            danger: "无"),
        .init(rule: "Bash(brew list:*)",        risk: .l1, purpose: "已装软件列表",       danger: "无"),
        .init(rule: "Bash(brew info:*)",        risk: .l1, purpose: "软件详情",           danger: "无"),
        .init(rule: "Read",                     risk: .l1, purpose: "读文件工具",         danger: "限制在授权目录内"),
        .init(rule: "Glob",                     risk: .l1, purpose: "按模式查找文件",     danger: "无"),
        .init(rule: "Grep",                     risk: .l1, purpose: "内容搜索",           danger: "无"),

        // ─────── L2 网络读 ───────
        .init(rule: "Bash(curl:*)",             risk: .l2, purpose: "HTTP 请求",           danger: "可用于外发数据，建议限定域名"),
        .init(rule: "Bash(wget:*)",             risk: .l2, purpose: "下载",               danger: "同上"),
        .init(rule: "Bash(ping:*)",             risk: .l2, purpose: "网络连通性",         danger: "无"),
        .init(rule: "Bash(dig:*)",              risk: .l2, purpose: "DNS 查询",           danger: "无"),
        .init(rule: "Bash(nslookup:*)",         risk: .l2, purpose: "DNS 查询",           danger: "无"),
        .init(rule: "Bash(git fetch:*)",        risk: .l2, purpose: "拉远端引用",         danger: "不修改工作区"),
        .init(rule: "Bash(git ls-remote:*)",    risk: .l2, purpose: "查远端引用",         danger: "无"),
        .init(rule: "Bash(git pull:*)",         risk: .l2, purpose: "拉取并合并",         danger: "可能触发合并冲突"),
        .init(rule: "Bash(gh pr view:*)",       risk: .l2, purpose: "查看 PR",             danger: "只读 GitHub"),
        .init(rule: "Bash(gh issue view:*)",    risk: .l2, purpose: "查看 issue",          danger: "只读"),
        .init(rule: "Bash(gh repo view:*)",     risk: .l2, purpose: "查看仓库",           danger: "只读"),
        .init(rule: "Bash(gh pr list:*)",       risk: .l2, purpose: "列 PR",               danger: "只读"),
        .init(rule: "Bash(gh api:*)",           risk: .l2, purpose: "GitHub API 调用",     danger: "取决于 HTTP 方法"),
        .init(rule: "WebFetch",                 risk: .l2, purpose: "抓网页",             danger: "可能抓到钓鱼内容"),
        .init(rule: "WebSearch",                risk: .l2, purpose: "搜索网页",           danger: "无"),

        // ─────── L3 写入 / 本地修改 / 安装 ───────
        .init(rule: "Bash(mkdir:*)",            risk: .l3, purpose: "新建目录",           danger: "无"),
        .init(rule: "Bash(touch:*)",            risk: .l3, purpose: "创建空文件",         danger: "无"),
        .init(rule: "Bash(cp:*)",               risk: .l3, purpose: "复制",               danger: "可能覆盖"),
        .init(rule: "Bash(mv:*)",               risk: .l3, purpose: "移动/重命名",         danger: "可能覆盖"),
        .init(rule: "Bash(chmod:*)",            risk: .l3, purpose: "改权限",             danger: "可能放开权限"),
        .init(rule: "Bash(tar:*)",              risk: .l3, purpose: "打包/解包",           danger: "解包可能覆盖"),
        .init(rule: "Bash(zip:*)",              risk: .l3, purpose: "压缩",               danger: "无"),
        .init(rule: "Bash(unzip:*)",            risk: .l3, purpose: "解压",               danger: "可能覆盖"),
        .init(rule: "Bash(git add:*)",          risk: .l3, purpose: "暂存",               danger: "无"),
        .init(rule: "Bash(git commit:*)",       risk: .l3, purpose: "本地提交",           danger: "可修改历史"),
        .init(rule: "Bash(git checkout:*)",     risk: .l3, purpose: "切换/还原",           danger: "可覆盖未提交改动"),
        .init(rule: "Bash(git switch:*)",       risk: .l3, purpose: "切换分支",           danger: "同上"),
        .init(rule: "Bash(git stash:*)",        risk: .l3, purpose: "暂存/恢复",           danger: "无"),
        .init(rule: "Bash(git merge:*)",        risk: .l3, purpose: "合并分支",           danger: "可能产生冲突"),
        .init(rule: "Bash(git rebase:*)",       risk: .l3, purpose: "变基",               danger: "修改本地历史"),
        .init(rule: "Bash(git cherry-pick:*)",  risk: .l3, purpose: "挑拣提交",           danger: "无"),
        .init(rule: "Bash(npm install:*)",      risk: .l3, purpose: "装 npm 包",          danger: "可能执行恶意 postinstall"),
        .init(rule: "Bash(pnpm install:*)",     risk: .l3, purpose: "装 pnpm 包",         danger: "同上"),
        .init(rule: "Bash(yarn:*)",             risk: .l3, purpose: "yarn 命令",          danger: "同上"),
        .init(rule: "Bash(npm run:*)",          risk: .l3, purpose: "跑 npm script",       danger: "取决于脚本内容"),
        .init(rule: "Bash(pip install:*)",      risk: .l3, purpose: "装 Python 包",        danger: "可能执行 setup.py"),
        .init(rule: "Bash(go build:*)",         risk: .l3, purpose: "Go 构建",            danger: "无"),
        .init(rule: "Bash(go test:*)",          risk: .l3, purpose: "Go 测试",            danger: "测试可能有副作用"),
        .init(rule: "Bash(go run:*)",           risk: .l3, purpose: "Go 运行",            danger: "取决于代码"),
        .init(rule: "Bash(go mod:*)",           risk: .l3, purpose: "Go 模块管理",        danger: "可能下载依赖"),
        .init(rule: "Bash(cargo build:*)",      risk: .l3, purpose: "Rust 构建",          danger: "无"),
        .init(rule: "Bash(cargo test:*)",       risk: .l3, purpose: "Rust 测试",          danger: "可能有副作用"),
        .init(rule: "Bash(cargo add:*)",        risk: .l3, purpose: "加 crate 依赖",      danger: "拉取 crate"),
        .init(rule: "Bash(make:*)",             risk: .l3, purpose: "构建",               danger: "Makefile 可含任意命令"),
        .init(rule: "Bash(docker build:*)",     risk: .l3, purpose: "构建镜像",           danger: "无"),
        .init(rule: "Bash(docker run:*)",       risk: .l3, purpose: "运行容器",           danger: "取决于镜像"),
        .init(rule: "Bash(docker compose:*)",   risk: .l3, purpose: "compose 操作",       danger: "启停容器"),
        .init(rule: "Bash(python:*)",           risk: .l3, purpose: "执行 Python",         danger: "取决于脚本"),
        .init(rule: "Bash(node:*)",             risk: .l3, purpose: "执行 Node",           danger: "取决于脚本"),
        .init(rule: "Bash(brew install:*)",     risk: .l3, purpose: "装软件",             danger: "修改系统"),
        .init(rule: "Bash(brew update)",        risk: .l3, purpose: "更新索引",           danger: "无"),
        .init(rule: "Bash(brew upgrade:*)",     risk: .l3, purpose: "升级软件",           danger: "可能破坏依赖"),
        .init(rule: "Edit",                     risk: .l3, purpose: "编辑文件工具",       danger: "仅对授权目录生效"),
        .init(rule: "Write",                    risk: .l3, purpose: "写文件工具",         danger: "同上"),
        .init(rule: "NotebookEdit",             risk: .l3, purpose: "编辑 notebook",       danger: "同上"),

        // ─────── L4 网络写 / 对外可见 ───────
        .init(rule: "Bash(git push:*)",         risk: .l4, purpose: "推送",               danger: "修改远程仓库"),
        .init(rule: "Bash(gh pr create:*)",     risk: .l4, purpose: "创建 PR",             danger: "对外可见"),
        .init(rule: "Bash(gh pr edit:*)",       risk: .l4, purpose: "编辑 PR",             danger: "对外可见"),
        .init(rule: "Bash(gh pr merge:*)",      risk: .l4, purpose: "合并 PR",             danger: "改主干"),
        .init(rule: "Bash(gh pr comment:*)",    risk: .l4, purpose: "PR 评论",             danger: "对外可见"),
        .init(rule: "Bash(gh issue create:*)",  risk: .l4, purpose: "创建 issue",          danger: "对外可见"),
        .init(rule: "Bash(gh release create:*)", risk: .l4, purpose: "发布 Release",       danger: "对外可见"),
        .init(rule: "Bash(docker push:*)",      risk: .l4, purpose: "推镜像",             danger: "改远程 registry"),
        .init(rule: "Bash(npm publish:*)",      risk: .l4, purpose: "发 npm 包",           danger: "对外可见且不可撤销"),
        .init(rule: "Bash(kubectl apply:*)",    risk: .l4, purpose: "部署 K8s 资源",       danger: "改集群"),
        .init(rule: "Bash(kubectl rollout:*)",  risk: .l4, purpose: "滚动发布",           danger: "改集群"),
        .init(rule: "Bash(terraform apply:*)",  risk: .l4, purpose: "应用 tf 计划",        danger: "改基础设施"),
        .init(rule: "Bash(aws:*)",              risk: .l4, purpose: "AWS CLI",            danger: "可能改云资源"),
        .init(rule: "Bash(gcloud:*)",           risk: .l4, purpose: "GCP CLI",            danger: "可能改云资源"),
        .init(rule: "Bash(scp:*)",              risk: .l4, purpose: "远程拷贝",           danger: "对外传输"),
        .init(rule: "Bash(rsync:*)",            risk: .l4, purpose: "增量同步",           danger: "远端时对外写"),

        // ─────── L5 破坏性 / 不可逆 ───────
        .init(rule: "Bash(rm:*)",                       risk: .l5, purpose: "删文件",             danger: "不可逆"),
        .init(rule: "Bash(rm -rf:*)",                   risk: .l5, purpose: "递归强删",           danger: "极度危险"),
        .init(rule: "Bash(git reset --hard:*)",         risk: .l5, purpose: "硬重置",             danger: "丢失未提交改动"),
        .init(rule: "Bash(git clean -fd:*)",            risk: .l5, purpose: "清理未跟踪",         danger: "不可逆"),
        .init(rule: "Bash(git push --force:*)",         risk: .l5, purpose: "强推",               danger: "覆盖远程历史"),
        .init(rule: "Bash(git push -f:*)",              risk: .l5, purpose: "强推(短)",           danger: "同上"),
        .init(rule: "Bash(git branch -D:*)",            risk: .l5, purpose: "强删分支",           danger: "丢失未合并工作"),
        .init(rule: "Bash(git tag -d:*)",               risk: .l5, purpose: "删 tag",              danger: "若已推出需强删远端"),
        .init(rule: "Bash(git commit --no-verify:*)",   risk: .l5, purpose: "跳过 hook",           danger: "绕过 lint/安全检查"),
        .init(rule: "Bash(sudo:*)",                     risk: .l5, purpose: "提权",               danger: "系统级改动"),
        .init(rule: "Bash(dd:*)",                       risk: .l5, purpose: "底层复制",           danger: "可毁磁盘"),
        .init(rule: "Bash(shutdown:*)",                 risk: .l5, purpose: "关机",               danger: "系统级"),
        .init(rule: "Bash(killall:*)",                  risk: .l5, purpose: "批量杀进程",         danger: "可能误伤"),
        .init(rule: "Bash(brew uninstall:*)",           risk: .l5, purpose: "卸载软件",           danger: "影响系统"),
        .init(rule: "Bash(npm uninstall:*)",            risk: .l5, purpose: "卸载 npm 包",        danger: "破坏依赖"),
        .init(rule: "Bash(docker system prune:*)",      risk: .l5, purpose: "清空 docker 状态",    danger: "数据丢失"),
        .init(rule: "Bash(docker volume rm:*)",         risk: .l5, purpose: "删卷",               danger: "数据丢失"),
        .init(rule: "Bash(kubectl delete:*)",           risk: .l5, purpose: "删 K8s 资源",        danger: "不可逆"),
        .init(rule: "Bash(terraform destroy:*)",        risk: .l5, purpose: "销毁基础设施",       danger: "极度危险"),
    ]

    static func risk(for rule: String) -> RiskLevel {
        all.first { $0.rule == rule }?.risk ?? .l3
    }
}
